Hyeongjin
HJ0623/java-lotto-6 pull request #1
Opened 2024-09-22 10:41 UTC by HJ0623

봐주셔서 감사합니다

2024-09-23 13:00 UTC, yeonkkk requested changes

2024-09-23 13:00 UTC, yeonkkk commented on src/main/java/lotto/Application.java
> +                        .toList();
아래 경우 어떤 결과가 나올까?

1. 유저가 당첨 번호로 `1 2 3 4 5 6`를 입력
2. 유저가 당첨 번호로 `5,5,5,5,5,5`를 입력

2024-09-23 13:00 UTC, yeonkkk commented on src/main/java/lotto/Application.java
> +                    }
```suggestion
                for (int winningNumber : winningNumbers) {
                    if (!(1 <= winningNumber && winningNumber <= 45)) {
                        throw new IllegalArgumentException("[ERROR] 당첨번호는 1~45사이의 숫자입니다");
                    }
```
다수의 당첨번호를 담고 있는 리스트 이름을 winningNumbers 로 지으면, 이해가 더 잘 되지 않을까? 🙂

2024-09-23 13:00 UTC, yeonkkk commented on src/main/java/lotto/Application.java
> +                }
`bonusMatchCount` 만 봤을 때 어떤 의미로 해석할 수 있을까?
1. 보너스번호 개수
2. 보너스번호를 로또가 포함하는지에 대한 T/F 값

2024-09-23 13:00 UTC, yeonkkk commented on src/main/java/lotto/Application.java
> +            System.out.printf("총 수익률은 %.2f%%입니다.", profitRate);
어떤 출력은 문자열을 합치고 있고, 어떤 출력은 String format 을 쓰고 있네!
기준이 궁금해~

2024-09-23 13:00 UTC, yeonkkk commented on src/main/java/lotto/Application.java
> +                    totalPrize += 5000;
enum을 쓰지 않더라도 같은 특성을 가지는 값들을 모아서 관리할 수 있어.
자료구조 중 Map에 대해 공부해보면 좋을 것 같아!

2024-09-23 13:00 UTC, yeonkkk commented on src/main/java/lotto/Application.java
> +        {
요 블럭은 어떤 의미로 사용한건지 궁금해!

2024-09-23 13:00 UTC, yeonkkk commented on src/main/java/lotto/Application.java
> +                if (inputMoney < 1000) {
`1000` 이라는 숫자가 계속 반복되네 ~
로또 게임을 할 때, 중요한 의미를 가지는 수인 것 같아!
이름을 붙여준다면, 요구사항이 변했을 때 실수 없이 바꿀 수 있겠다.

예) 기준 금액이 1000원이 아니라 2000원이 된다면?

2024-09-23 13:00 UTC, yeonkkk commented on src/main/java/lotto/Application.java
> +                        .toList();
오호 스트림도 쓸 줄 아는구나!👍

2024-09-23 13:00 UTC, yeonkkk commented on docs/README.md
> +7.(당첨금액/구입금액) 해서 수익률 계산하고 출력
열심히 검증한 내용들도 기능 명세에 들어갈 수 있겠다!
예를 들면, `당첨번호는 숫자만 입력할 수 있다` 같은 것들

2024-09-23 13:00 UTC, yeonkkk commented on docs/README.md
> +# 로또 실행 순서
휴일동안 과제하느라 고생했어!👍
클래스, 메서드 분리하지 않으니까 더 쉽지? 훨씬 자연스럽다 ~
지금처럼 기능 구현 자체가 너무 어렵게 느껴진다면, 다 작성하고 분리하는 연습하는 것도 좋을 것 같아.
클래스, 메서드를 분리해야 할 필요성을 느끼고, 훈련이 된 후에 구조 잡는 연습을 하는 방법도 있으니까 ~:)

기능을 잘 구현해줬으니, 이제 메서드 분리를 해보자! (클래스 분리X)
1. 기능(역할)이 분리되는 것 같은 부분 -> 예) 구입 금액이 1000원인지 검증
2. 이름을 붙이면 좋을 것 같은 부분  -> 예) `validateMinimumPrice` (구입 금액이 1000원인지 검증)

모든 코드를 분리할 필요 없어. 너가 해야할 것 같은 곳만 하면 돼!
고생했어! 위 내용과 코멘트들 반영하고 다시 요청해줘 :)

2024-09-23 15:31 UTC, HJ0623 commented on src/main/java/lotto/Application.java
> +        {
이부분은 원래 아래에서 선언을 했었는데 try부분을 나중에 쓸려고하니깐 try내부에서만 선언이 되어서 밖으로 뺏습니당

2024-09-23 15:36 UTC, HJ0623 commented on src/main/java/lotto/Application.java
> +                        .toList();
1번은 숫자로 인식을 못하는것 같고 2번은 예외처리를 못하고 그냥 넘어가네요 고쳐보겠습니다!

2024-10-21 07:21 UTC, HJ0623 commented on src/main/java/lotto/Application.java
> +            System.out.printf("총 수익률은 %.2f%%입니다.", profitRate);
첫 번째. System.out.printf() 사용
두 번째. String.format() 사용
세 번째. Math.round() 사용 소수점을 출력하려면 3가지중 하나라고 해서 printf사용하는게 제일 간단해서 했어서 그렇게 했는데 통일하는게 좋을거 같아서 다시 바꿧습니다!

2024-10-21 07:40 UTC, HJ0623 commented on src/main/java/lotto/Application.java
> +                if (inputMoney < 1000) {
public static final int minInputMoney = 1000; 이라고 선언해줬습니다!

2024-11-06 01:49 UTC, HJ0623 commented on src/main/java/lotto/Application.java
> +                    }
이 배열은 입력받은 당첨번호를 담고있다고 생각해서 이렇게 적는게 더 이해가 잘될것 같다고 생각해서 바꾸지 
않았습니다!

2024-11-11 18:13 UTC, HJ0623 commented on src/main/java/lotto/Application.java
> +                    }
> 이 리스트는 입력받은 당첨번호를 담고있다고 생각해서 이렇게 적는게 더 이해가 잘될것 같다고 생각해서 바꾸지 않았습니다!

2024-11-11 18:17 UTC, HJ0623 commented on src/main/java/lotto/Application.java
> +                }
boolean 인데 굳이 count라는 이름을 할 필요가 없었던것같아요 isBonusNumberMatched로 바꿧습니다!

2024-11-11 18:43 UTC, HJ0623 commented
• 코드 확인을 제대로 하지 않고 Commit 후 Push하여 Pull Request를 한 경우, PR 수정 방법이 필요하다.
• PR을 Closed하고 다시 보내는 방법 외에, 수정한 부분만 자동으로 PR에 반영하는 방법이 있다.
• 수정한 내용을 git add 한 후, git commit —amend를 통해 최신 commit을 덮어쓴다.
• 이후 git push -f origin {branch-name}을 통해 이미 올라간 PR에 수정한 부분만 자동으로 반영하면, 다시 PR을 진행하지 않아도 된다. 이 방식으로 해봤는데 잘됐는진 잘모르겠어요,, Merge Pull Request를 또 다시 해야하는건지??  그리고 중복되는 커밋이 많은데 실수로 푸쉬안누르고해서 그렇습니다 제일 처음에 커밋한걸로 봐주시면 감사하겠습니다

2024-11-12 02:26 UTC, closed without merging