Hyeongjin
HJ0623/java-lotto-6 pull request #1
Opened 2024-08-27 13:47 UTC by HJ0623

2024-08-29 12:48 UTC, yeonkkk requested changes
아픈데 과제하느라고 고생했어~
이번에도 코멘트에 답글 달아주고, 리팩토링하자!

2024-08-29 12:48 UTC, yeonkkk commented on src/main/java/lotto/Validator.java
> +            System.out.println("[ERROR] 금액은 천원 단위이어야 합니다.");
예외 상황에서 메세지를 출력할 수 있도록 처리 잘 해줬네 ~!
지금은 모든 검증 로직에서 println() 을 수행하고 있는데, validate 에 예외 메세지를 출력하기 보단 공통으로 처리할 수 있는 방법을 찾아보면 어떨까?!

try-catch 문에 대해 알아보면 좋을 것 같아~~

2024-08-29 12:48 UTC, yeonkkk commented on src/main/java/lotto/LottoVariable.java
> +    int bonusNumber; // 보너스번호
필드만 가지는 클래스인데, 필드들이 다 default로 선언되어 있네~
이렇게 구현한 이유가 있을까?

2024-08-29 12:48 UTC, yeonkkk commented on src/main/java/lotto/Monitor.java
> +    }
LottoVariable을 파라미터로 주고, 메서드 내부에서 상태 값을 넣어주고 있어. 
어떤 문제가 발생할 수 있을까?

2024-08-29 12:48 UTC, yeonkkk commented on src/main/java/lotto/Monitor.java
> +    }
```suggestion
    public void WinningNumbers(LottoVariable lottoVariable) {
        System.out.println("당첨 번호를 입력해 주세요.");
        lottoVariable.selectNumber.addAll(
                Arrays.stream(Console.readLine().split(","))
                .map(Integer::parseInt)
                        .toList()
                        );
    }
```
라인을 구분하면 가독성이 더 좋을 것 같다~

2024-08-29 12:48 UTC, yeonkkk commented on src/main/java/lotto/Monitor.java
> +    public void WinningNumbers(LottoVariable lottoVariable) {
메서드명 다시 고민해보자 ~

2024-08-29 12:48 UTC, yeonkkk commented on src/main/java/lotto/Monitor.java
> +    public void BonusNumber(LottoVariable lottoVariable) {
메서드들에 다 메서드명에 대한 내용을 적는건 의미가 없을 것 같아서, 여기에 적을게.
지난 과제를 하면서 네이밍에 대해 어느정도 잘 알고 있다고 생각했는데, 이번 과제들은 네이밍이 중구난방인 것 같아.

기능을 구현하고 성능을 향상 시키는 것도 정말 중요한 일이지만, 네이밍을 하는 것도 신경써야해.
개발을 할 때는 다른 사람들과 협업하는 일이 많기 때문에 의미를 명확하게 적어주는 것이 좋고, 관례를 따르는 것이 중요해.
협업을 하지 않더라도, 누군가는 내가 작성한 코드를 보고 참고할 수 있고 내가 작성한 코드를 유지보수 할수도 있겠지.

그렇기 때문에 코드 구조, 네이밍도 신경써서 하는게 좋아.
리팩토링하면서 좀 더 생각해보고 진행하면 좋을 것 같다!

2024-08-29 12:48 UTC, yeonkkk commented on src/main/java/lotto/Monitor.java
> +    }
enum의 ordinal()을 사용한 이유가 있을까?

2024-08-29 12:48 UTC, yeonkkk commented on src/main/java/lotto/Monitor.java
> +    }
추가로 StringBuilder에 대해 알아보면 좋을 것 같아

2024-08-29 12:48 UTC, yeonkkk commented on src/main/java/lotto/Profit.java
> +}
finalI는 어떤 용도이니?
그리고 이 메서드의 동작 과정을 코멘트에 한번 달아봐 줬으면 좋겠어.

2024-08-29 12:48 UTC, yeonkkk commented on src/main/java/lotto/Profit.java
> +}
그리고 get 메서드인데 return 값이 없구나

2024-09-03 08:47 UTC, HJ0623 commented on src/main/java/lotto/Monitor.java
> +    public void BonusNumber(LottoVariable lottoVariable) {
네 나름 고민하고 메서드명을 지은건데 다시한번 고민해보겠습니다 ㅜㅜ

2024-09-03 09:40 UTC, HJ0623 commented on src/main/java/lotto/Validator.java
> +        System.out.printf("%d개를 구매했습니다.\n", money / 1000);
이 부분은 빼는게 좋을까요 ??

2024-09-03 10:26 UTC, HJ0623 commented on src/main/java/lotto/Monitor.java
> +    public void BonusNumber(LottoVariable lottoVariable) {
제가 다시 보니깐 대문자 구분도 제대로 안하고 좀 중구난방이네요 고쳐보겠습니다!!

2024-09-05 01:58 UTC, HJ0623 commented on src/main/java/lotto/Monitor.java
> +    }
넵 확인했습니다!

2024-09-09 06:04 UTC, HJ0623 commented on src/main/java/lotto/LottoVariable.java
> +public class LottoVariable {
많이 쓸거 같은애들을 한군데에 모으면 더 보기 편하지 않을까? 라고 생각했는데 별로 일까용,,

2024-09-09 06:33 UTC, HJ0623 commented on src/main/java/lotto/LottoVariable.java
> +public class LottoVariable {
필드만 있는클래스의 문제점

캡슐화위반

객체지향에서는 필드와 메서드가 같이 있는게 일반적임 ,이건 절차적 프로그래밍 안쓰는 이유가 있었네용

2024-09-09 06:52 UTC, HJ0623 commented on src/main/java/lotto/Monitor.java
> +    }
4.enum에서 ordinal을 사용하지않는 이유
enum대신 객체필드를 사용하자
유지보수에 매우 안좋음 -> ordinal이란 메서드는 enum 자료형 안에서 enum 상수의 위치를 나타내는 정수값을 반환함 상수의 순서가 바뀌거나 그러면 문제가 발생함 -> 걍쓰지말자 잘 몰라서 썻었는데 바로 나와서 수정했습니다..

2024-09-09 07:35 UTC, HJ0623 commented on src/main/java/lotto/Monitor.java
> +    }
캡슐화에 문제가있다?? 정보 은닉에 문제가있다? 이런느낌인거같아요

2024-09-09 08:48 UTC, HJ0623 commented on src/main/java/lotto/Prize.java
> +        return lottoPrizeValue;
넵!!

2024-09-09 09:05 UTC, HJ0623 commented on src/main/java/lotto/Validator.java
> +public class Validator {
넵! 확인했습니다

2024-09-09 09:06 UTC, HJ0623 commented on src/main/java/lotto/Validator.java
> +    }
넵 고쳐보겠습니다!

2024-09-09 09:06 UTC, HJ0623 commented on docs/README.md
> +- 당첨 번호 추첨 시 중복되지 않는 숫자 6개와 보너스 번호 1개를 뽑는다.
넵 확인했습니다!

2024-09-09 09:11 UTC, HJ0623 commented on src/main/java/lotto/LottoNumberChecker.java
> +    int correctNumberCount;
이 클래스 or 변수는 이 클래스 안에서만 사용하네? -> private
이 클래스 or 변수는 같은 패키지 안에서만 사용하네? -> default (안 붙임)
이 클래스 or 변수는 다른 패키지의 자손클래스에서도 사용하네? -> protected
이 클래스 or 변수는 다른 패키지에서 막 가져다 사용하네? -> public
이거보고 하는데 아직은 좀 오락가락하는거같아요

2024-09-09 10:13 UTC, HJ0623 commented on src/main/java/lotto/Profit.java
> +}
사실 gpt에다가 물어보고 이해한줄알아서 썻는데  다시보니깐 코드가 뭔소린지 솔직히 잘모르겠네요 죄송합니다 /// 
  1) 'private'이 할당된 변수에 대한 정보만 읽고 싶다면?

      → get() 메서드

  2) 'private'이 할당된 변수에 대해 수정이 필요하다면?

      → set() 메서드


get() 메서드
  - 'private'로 선언된 멤버변수(필드)에 대해 접근해서 값을 읽을 수 있는 메서드 (read-only)

  - 반드시 'return' 키워드를 필요로 함
  
쓸떈 잘몰랐는데 다시 찾아봐서 공부하는 중입니다 ,,

2024-09-09 11:24 UTC, merged